* :app regex

#+begin_quote
This module is a work in progress.
#+end_quote

This module adds a Perl-Compatible Regular Expression IDE to Emacs, inspired by [[http://regexr.com/][regexr.com]].

#+begin_quote
To hone my regex fu, I need a regex playground. Sure, there's regexr.com, but don't be silly, that's not Emacs!

Sadly, the Emacs' regex syntax is niche and lacks support for a few useful features like lookaround assertions, conditionals, case modifiers or backreferences. No, I want PCRE. I am going to have my cake and eat it too, damn it!
#+end_quote

** Install
This module requires =perl= (5.0 minimum) for the perl backend (the default), which should be available by default on most Unix systems.

** Usage
This module can be invoked via ~M-x =regex~.

*** Workflow
1. Invoke `=regex' (if opened with C-u, opens in separate workspace with a dummy text buffer).
2. A regex window will popup up. Any matches will be highlighted in the original buffer.
3. =C-c C-k= to close it
4. *TODO* =C-c C-e= to export to various langauges
